# Package the libray using build (ahttps://pypa-build.readthedocs.io/en/latest/)

on:
  release:
    types: [released]
    branches: 
      -master

jobs:
  build_package:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Build package
      run: |
        pip install build
        python -m build

    - name: Configure git
      run: |
        git config --global user.email "carter.marshall@gmail.com"
        git config --global user.name "marshackVB"
        git commit -a -m "Update wheel release version"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
