# Package the libray using build (ahttps://pypa-build.readthedocs.io/en/latest/)

on: 
  push:
    branches:
     - master

jobs:
  build_package:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - uses: actions/checkout@v3
      with:
        ref: master
    - run: |
        pip install build
        python -m build
        git config --global user.email "carter.marshall@gmail.com"
        git config --global user.name "marshackVB"
        git commit -a -m "Update wheel release version"
