# Package the libray using build (ahttps://pypa-build.readthedocs.io/en/latest/)

on:
  release:
    types: [released]
    branches: 
      -master

jobs:
  build_package:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - uses: actions/checkout@v3
      with:
        ref: master
        
    - run: |
        git config user.email "carter.marshall@gmail.com"
        git config user.name "marshackVB"
        
    - run: |
        pip install build
        python3 -m build
        git add -f ./dist/*.whl
        git commit -m 'Update wheel release version'
        git push