# Package the libray using build (ahttps://pypa-build.readthedocs.io/en/latest/)

on:
  release:
    types: [released]
    branches: 
      -master

jobs:
  build_package:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
        
    - name: Build package
      run: |
        pip install build
        python -m build